<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:actormapping="http://www.bonitasoft.org/ns/actormapping/6.0" xmlns:configuration="http://www.bonitasoft.org/ns/bpm/configuration" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_s6Lk4E1oEfC2Nsglly8TUQ" name="V" version="1" bonitaModelVersion="8">
    <elements xmi:type="process:Pool" xmi:id="_s6Lk4U1oEfC2Nsglly8TUQ" name="Gardensnolife" version="1">
      <elements xmi:type="process:Lane" xmi:id="_s6Lk4k1oEfC2Nsglly8TUQ" name="Collaborateur" actor="_s6Llrk1oEfC2Nsglly8TUQ">
        <elements xmi:type="process:StartEvent" xmi:id="_s6Lk401oEfC2Nsglly8TUQ" name="Début" outgoing="_s6LljU1oEfC2Nsglly8TUQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_s6Lk5E1oEfC2Nsglly8TUQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_s6Lk5U1oEfC2Nsglly8TUQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_s6Lk5k1oEfC2Nsglly8TUQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_s6Lk501oEfC2Nsglly8TUQ" name="Saisir demande mission" outgoing="_s6Llk01oEfC2Nsglly8TUQ" incoming="_s6LljU1oEfC2Nsglly8TUQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_s6Lk6E1oEfC2Nsglly8TUQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_s6Lk6U1oEfC2Nsglly8TUQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_s6Lk6k1oEfC2Nsglly8TUQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_s6Lk601oEfC2Nsglly8TUQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_s6Lk7E1oEfC2Nsglly8TUQ" name="demandeMission" content="demandeMission" type="TYPE_VARIABLE" returnType="java.util.List">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_s6Lk7U1oEfC2Nsglly8TUQ" name="demandeMission" multiple="true" dataType="_s6Ll301oEfC2Nsglly8TUQ" className="com.gardensnolife.model.DemandeMission"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_s6Lk7k1oEfC2Nsglly8TUQ" name="demandeMissionInput" content="demandeMissionInput" type="TYPE_CONTRACT_INPUT" returnType="java.util.List">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_s6Lk701oEfC2Nsglly8TUQ" name="demandeMissionInput" type="COMPLEX" multiple="true"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_s6Lk8E1oEfC2Nsglly8TUQ" type="ASSIGNMENT" expression="addAll">
              <inputTypes>java.util.Collection</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_s6Lk8U1oEfC2Nsglly8TUQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_s6Lk8k1oEfC2Nsglly8TUQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_s6Lk801oEfC2Nsglly8TUQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_s6Lk9E1oEfC2Nsglly8TUQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_s6Lk9U1oEfC2Nsglly8TUQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_s6Lk9k1oEfC2Nsglly8TUQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_s6Lk901oEfC2Nsglly8TUQ" name="SaisirDemandeMission" content="da6ff340-b905-49dc-81dc-b24151072c1e" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_s6Lk-E1oEfC2Nsglly8TUQ">
            <inputs xmi:type="process:ContractInput" xmi:id="_s6Lk-U1oEfC2Nsglly8TUQ" name="demandeMissionInput" type="COMPLEX" multiple="true" dataReference="demandeMission">
              <inputs xmi:type="process:ContractInput" xmi:id="_s6Lk-k1oEfC2Nsglly8TUQ" name="persistenceId_string"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_s6Lk-01oEfC2Nsglly8TUQ" name="id"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_s6Lk_E1oEfC2Nsglly8TUQ" name="collaborateur"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_s6Lk_U1oEfC2Nsglly8TUQ" name="destination"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_s6Lk_k1oEfC2Nsglly8TUQ" name="dateDebut" type="OFFSETDATETIME"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_s6Lk_01oEfC2Nsglly8TUQ" name="dateFin" type="OFFSETDATETIME"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_s6LlAE1oEfC2Nsglly8TUQ" name="motif"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_s6LlAU1oEfC2Nsglly8TUQ" name="avanceFrais" type="DECIMAL"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_s6LlAk1oEfC2Nsglly8TUQ" name="decisionManager" type="BOOLEAN"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_s6LlA01oEfC2Nsglly8TUQ" name="decisionRH" type="BOOLEAN"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_s6LlBE1oEfC2Nsglly8TUQ" name="statut"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_s6LlBU1oEfC2Nsglly8TUQ" name="dateCreation" type="OFFSETDATETIME"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_s6LlBk1oEfC2Nsglly8TUQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_s6LlB01oEfC2Nsglly8TUQ" name="Manager" actor="_s6Llr01oEfC2Nsglly8TUQ">
        <elements xmi:type="process:Task" xmi:id="_s6LlCE1oEfC2Nsglly8TUQ" name="Etudier demande" outgoing="_s6Llok1oEfC2Nsglly8TUQ" incoming="_s6LlnE1oEfC2Nsglly8TUQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_s6LlCU1oEfC2Nsglly8TUQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_s6LlCk1oEfC2Nsglly8TUQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_s6LlC01oEfC2Nsglly8TUQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_s6LlDE1oEfC2Nsglly8TUQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_s6LlDU1oEfC2Nsglly8TUQ" name="decisionManager" content="decisionManager" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:Data" xmi:id="_s6LlDk1oEfC2Nsglly8TUQ" name="decisionManager" dataType="_s6Ll101oEfC2Nsglly8TUQ"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_s6LlD01oEfC2Nsglly8TUQ" name="decision" content="decision" type="TYPE_CONTRACT_INPUT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_s6LlEE1oEfC2Nsglly8TUQ" name="decision" type="BOOLEAN">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_s6LlEU1oEfC2Nsglly8TUQ"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_s6LlEk1oEfC2Nsglly8TUQ" type="ASSIGNMENT"/>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_s6LlE01oEfC2Nsglly8TUQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_s6LlFE1oEfC2Nsglly8TUQ" name="demandeMission" content="demandeMission" type="TYPE_VARIABLE" returnType="java.util.List">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_s6LlFU1oEfC2Nsglly8TUQ" name="demandeMission" multiple="true" dataType="_s6Ll301oEfC2Nsglly8TUQ" className="com.gardensnolife.model.DemandeMission"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_s6LlFk1oEfC2Nsglly8TUQ" name="newScript()" content="// Cloner l'objet existant avec la nouvelle décision&#xD;&#xA;if (demandeMission != null &amp;&amp; !demandeMission.isEmpty()) {&#xD;&#xA;    def mission = demandeMission.get(0)&#xD;&#xA;    mission.decisionManager = decision&#xD;&#xA;    return [mission]&#xD;&#xA;} else {&#xD;&#xA;    return demandeMission&#xD;&#xA;}" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_s6LlF01oEfC2Nsglly8TUQ" name="demandeMission" multiple="true" dataType="_s6Ll301oEfC2Nsglly8TUQ" className="com.gardensnolife.model.DemandeMission"/>
              <referencedElements xmi:type="process:ContractInput" xmi:id="_s6LlGE1oEfC2Nsglly8TUQ" name="decision" type="BOOLEAN">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_s6LlGU1oEfC2Nsglly8TUQ"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_s6LlGk1oEfC2Nsglly8TUQ" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_s6LlG01oEfC2Nsglly8TUQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_s6LlHE1oEfC2Nsglly8TUQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_s6LlHU1oEfC2Nsglly8TUQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_s6LlHk1oEfC2Nsglly8TUQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_s6LlH01oEfC2Nsglly8TUQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_s6LlIE1oEfC2Nsglly8TUQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_s6LlIU1oEfC2Nsglly8TUQ" name="EtudierDemande" content="5e7fe357-b84d-4080-a04c-efb0a761538c" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_s6LlIk1oEfC2Nsglly8TUQ">
            <inputs xmi:type="process:ContractInput" xmi:id="_s6LlI01oEfC2Nsglly8TUQ" name="decision" type="BOOLEAN">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_s6LlJE1oEfC2Nsglly8TUQ"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_s6LlJU1oEfC2Nsglly8TUQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_s6LlJk1oEfC2Nsglly8TUQ" name="Gateway1" outgoing="_s6Lllk1oEfC2Nsglly8TUQ _s6LlnE1oEfC2Nsglly8TUQ" incoming="_s6Llk01oEfC2Nsglly8TUQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_s6LlJ01oEfC2Nsglly8TUQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_s6LlKE1oEfC2Nsglly8TUQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_s6LlKU1oEfC2Nsglly8TUQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_s6LlKk1oEfC2Nsglly8TUQ" name="Réétudier demande (Manager)" outgoing="_s6Llq01oEfC2Nsglly8TUQ" incoming="_s6LlpU1oEfC2Nsglly8TUQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_s6LlK01oEfC2Nsglly8TUQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_s6LlLE1oEfC2Nsglly8TUQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_s6LlLU1oEfC2Nsglly8TUQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_s6LlLk1oEfC2Nsglly8TUQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_s6LlL01oEfC2Nsglly8TUQ" name="decisionManager" content="decisionManager" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:Data" xmi:id="_s6LlME1oEfC2Nsglly8TUQ" name="decisionManager" dataType="_s6Ll101oEfC2Nsglly8TUQ"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_s6LlMU1oEfC2Nsglly8TUQ" name="decision" content="decision" returnType="java.lang.Boolean"/>
            <operator xmi:type="expression:Operator" xmi:id="_s6LlMk1oEfC2Nsglly8TUQ" type="ASSIGNMENT"/>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_s6LlM01oEfC2Nsglly8TUQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_s6LlNE1oEfC2Nsglly8TUQ" name="demandeMission" content="demandeMission" type="TYPE_VARIABLE" returnType="java.util.List">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_s6LlNU1oEfC2Nsglly8TUQ" name="demandeMission" multiple="true" dataType="_s6Ll301oEfC2Nsglly8TUQ" className="com.gardensnolife.model.DemandeMission"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_s6LlNk1oEfC2Nsglly8TUQ" name="newScript()" content="// Cloner l'objet existant avec la nouvelle décision&#xD;&#xA;if (demandeMission != null &amp;&amp; !demandeMission.isEmpty()) {&#xD;&#xA;    def mission = demandeMission.get(0)&#xD;&#xA;    mission.decisionManager = decision&#xD;&#xA;    return [mission]&#xD;&#xA;} else {&#xD;&#xA;    return demandeMission&#xD;&#xA;}" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_s6LlN01oEfC2Nsglly8TUQ" name="decision" type="BOOLEAN">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_s6LlOE1oEfC2Nsglly8TUQ"/>
              </referencedElements>
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_s6LlOU1oEfC2Nsglly8TUQ" name="demandeMission" multiple="true" dataType="_s6Ll301oEfC2Nsglly8TUQ" className="com.gardensnolife.model.DemandeMission"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_s6LlOk1oEfC2Nsglly8TUQ" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_s6LlO01oEfC2Nsglly8TUQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_s6LlPE1oEfC2Nsglly8TUQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_s6LlPU1oEfC2Nsglly8TUQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_s6LlPk1oEfC2Nsglly8TUQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_s6LlP01oEfC2Nsglly8TUQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_s6LlQE1oEfC2Nsglly8TUQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_s6LlQU1oEfC2Nsglly8TUQ" name="EtudierDemande" content="5e7fe357-b84d-4080-a04c-efb0a761538c" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_s6LlQk1oEfC2Nsglly8TUQ">
            <inputs xmi:type="process:ContractInput" xmi:id="_s6LlQ01oEfC2Nsglly8TUQ" name="decision" type="BOOLEAN">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_s6LlRE1oEfC2Nsglly8TUQ"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_s6LlRU1oEfC2Nsglly8TUQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_s6LlRk1oEfC2Nsglly8TUQ" name="Service RH" actor="_s6LlsE1oEfC2Nsglly8TUQ">
        <elements xmi:type="process:Task" xmi:id="_s6LlR01oEfC2Nsglly8TUQ" name="Analyser opportunité" outgoing="_s6Lln01oEfC2Nsglly8TUQ" incoming="_s6Lllk1oEfC2Nsglly8TUQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_s6LlSE1oEfC2Nsglly8TUQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_s6LlSU1oEfC2Nsglly8TUQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_s6LlSk1oEfC2Nsglly8TUQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_s6LlS01oEfC2Nsglly8TUQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_s6LlTE1oEfC2Nsglly8TUQ" name="decisionRH" content="decisionRH" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:Data" xmi:id="_s6LlTU1oEfC2Nsglly8TUQ" name="decisionRH" dataType="_s6Ll101oEfC2Nsglly8TUQ"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_s6LlTk1oEfC2Nsglly8TUQ" name="decision" content="decision" type="TYPE_CONTRACT_INPUT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_s6LlT01oEfC2Nsglly8TUQ" name="decision" type="BOOLEAN">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_s6LlUE1oEfC2Nsglly8TUQ"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_s6LlUU1oEfC2Nsglly8TUQ" type="ASSIGNMENT"/>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_s6LlUk1oEfC2Nsglly8TUQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_s6LlU01oEfC2Nsglly8TUQ" name="demandeMission" content="demandeMission" type="TYPE_VARIABLE" returnType="java.util.List">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_s6LlVE1oEfC2Nsglly8TUQ" name="demandeMission" multiple="true" dataType="_s6Ll301oEfC2Nsglly8TUQ" className="com.gardensnolife.model.DemandeMission"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_s6LlVU1oEfC2Nsglly8TUQ" name="newScript()" content="// Mettre à jour l'objet avec la décision RH&#xD;&#xA;if (demandeMission != null &amp;&amp; !demandeMission.isEmpty()) {&#xD;&#xA;    def mission = demandeMission.get(0)&#xD;&#xA;    mission.decisionRH = decision&#xD;&#xA;    return [mission]&#xD;&#xA;} else {&#xD;&#xA;    return demandeMission&#xD;&#xA;}" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_s6LlVk1oEfC2Nsglly8TUQ" name="demandeMission" multiple="true" dataType="_s6Ll301oEfC2Nsglly8TUQ" className="com.gardensnolife.model.DemandeMission"/>
              <referencedElements xmi:type="process:ContractInput" xmi:id="_s6LlV01oEfC2Nsglly8TUQ" name="decision" type="BOOLEAN">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_s6LlWE1oEfC2Nsglly8TUQ"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_s6LlWU1oEfC2Nsglly8TUQ" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_s6LlWk1oEfC2Nsglly8TUQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_s6LlW01oEfC2Nsglly8TUQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_s6LlXE1oEfC2Nsglly8TUQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_s6LlXU1oEfC2Nsglly8TUQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_s6LlXk1oEfC2Nsglly8TUQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_s6LlX01oEfC2Nsglly8TUQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_s6LlYE1oEfC2Nsglly8TUQ" name="AnalyserOpportunite" content="8edb11b6-641f-4c97-9893-ac43a88f80eb" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_s6LlYU1oEfC2Nsglly8TUQ">
            <inputs xmi:type="process:ContractInput" xmi:id="_s6LlYk1oEfC2Nsglly8TUQ" name="decision" type="BOOLEAN">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_s6LlY01oEfC2Nsglly8TUQ"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_s6LlZE1oEfC2Nsglly8TUQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_s6LlZU1oEfC2Nsglly8TUQ" name="Notifier collaborateur" outgoing="_s6LlkE1oEfC2Nsglly8TUQ" incoming="_s6LlqE1oEfC2Nsglly8TUQ _s6Llq01oEfC2Nsglly8TUQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_s6LlZk1oEfC2Nsglly8TUQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_s6LlZ01oEfC2Nsglly8TUQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_s6LlaE1oEfC2Nsglly8TUQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_s6LlaU1oEfC2Nsglly8TUQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_s6Llak1oEfC2Nsglly8TUQ" name="demandeMission" content="demandeMission" type="TYPE_VARIABLE" returnType="java.util.List">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_s6Lla01oEfC2Nsglly8TUQ" name="demandeMission" multiple="true" dataType="_s6Ll301oEfC2Nsglly8TUQ" className="com.gardensnolife.model.DemandeMission"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_s6LlbE1oEfC2Nsglly8TUQ" name="newScript()" content="if (demandeMission != null &amp;&amp; !demandeMission.isEmpty()) {&#xD;&#xA;    def mission = demandeMission.get(0)&#xD;&#xA;    &#xD;&#xA;    if (decisionManager == decisionRH) {&#xD;&#xA;        // Réponses identiques - on suit la décision commune&#xD;&#xA;        mission.statut = decisionManager ? &quot;APPROUVEE&quot; : &quot;REFUSEE&quot;&#xD;&#xA;    } else {&#xD;&#xA;        // Réponses différentes - Manager a le dernier mot&#xD;&#xA;        mission.statut = decisionManager ? &quot;APPROUVEE&quot; : &quot;REFUSEE&quot;&#xD;&#xA;    }&#xD;&#xA;    &#xD;&#xA;    return [mission]&#xD;&#xA;} else {&#xD;&#xA;    return demandeMission&#xD;&#xA;}" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_s6LlbU1oEfC2Nsglly8TUQ" name="demandeMission" multiple="true" dataType="_s6Ll301oEfC2Nsglly8TUQ" className="com.gardensnolife.model.DemandeMission"/>
              <referencedElements xmi:type="process:Data" xmi:id="_s6Llbk1oEfC2Nsglly8TUQ" name="decisionManager" dataType="_s6Ll101oEfC2Nsglly8TUQ"/>
              <referencedElements xmi:type="process:Data" xmi:id="_s6Llb01oEfC2Nsglly8TUQ" name="decisionRH" dataType="_s6Ll101oEfC2Nsglly8TUQ"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_s6LlcE1oEfC2Nsglly8TUQ" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_s6LlcU1oEfC2Nsglly8TUQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_s6Llck1oEfC2Nsglly8TUQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_s6Llc01oEfC2Nsglly8TUQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_s6LldE1oEfC2Nsglly8TUQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_s6LldU1oEfC2Nsglly8TUQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_s6Lldk1oEfC2Nsglly8TUQ" name="Gateway2" outgoing="_s6LlmU1oEfC2Nsglly8TUQ" incoming="_s6Lln01oEfC2Nsglly8TUQ _s6Llok1oEfC2Nsglly8TUQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_s6Lld01oEfC2Nsglly8TUQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_s6LleE1oEfC2Nsglly8TUQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_s6LleU1oEfC2Nsglly8TUQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_s6Llek1oEfC2Nsglly8TUQ" name="Réponses identiques ?" outgoing="_s6LlpU1oEfC2Nsglly8TUQ _s6LlqE1oEfC2Nsglly8TUQ" incoming="_s6LlmU1oEfC2Nsglly8TUQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_s6Lle01oEfC2Nsglly8TUQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_s6LlfE1oEfC2Nsglly8TUQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_s6LlfU1oEfC2Nsglly8TUQ" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_s6Llfk1oEfC2Nsglly8TUQ" name="Système">
        <elements xmi:type="process:EndEvent" xmi:id="_s6Llf01oEfC2Nsglly8TUQ" name="Fin" incoming="_s6LlkE1oEfC2Nsglly8TUQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_s6LlgE1oEfC2Nsglly8TUQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_s6LlgU1oEfC2Nsglly8TUQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_s6Llgk1oEfC2Nsglly8TUQ" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_s6Llg01oEfC2Nsglly8TUQ" name="demandeMission" multiple="true" dataType="_s6Ll301oEfC2Nsglly8TUQ" className="com.gardensnolife.model.DemandeMission">
        <defaultValue xmi:type="expression:Expression" xmi:id="_s6LlhE1oEfC2Nsglly8TUQ" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_s6LlhU1oEfC2Nsglly8TUQ" name="decisionManager" dataType="_s6Ll101oEfC2Nsglly8TUQ">
        <defaultValue xmi:type="expression:Expression" xmi:id="_s6Llhk1oEfC2Nsglly8TUQ" content="" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_s6Llh01oEfC2Nsglly8TUQ" name="decisionRH" dataType="_s6Ll101oEfC2Nsglly8TUQ">
        <defaultValue xmi:type="expression:Expression" xmi:id="_s6LliE1oEfC2Nsglly8TUQ" content="" returnType="java.lang.Boolean"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_s6LliU1oEfC2Nsglly8TUQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_s6Llik1oEfC2Nsglly8TUQ" name="SaisirDemandeMission" content="da6ff340-b905-49dc-81dc-b24151072c1e" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_s6Lli01oEfC2Nsglly8TUQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_s6LljE1oEfC2Nsglly8TUQ" name="EtudierDemande" content="5e7fe357-b84d-4080-a04c-efb0a761538c" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_s6LljU1oEfC2Nsglly8TUQ" target="_s6Lk501oEfC2Nsglly8TUQ" source="_s6Lk401oEfC2Nsglly8TUQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_s6Lljk1oEfC2Nsglly8TUQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_s6Llj01oEfC2Nsglly8TUQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_s6LlkE1oEfC2Nsglly8TUQ" target="_s6Llf01oEfC2Nsglly8TUQ" source="_s6LlZU1oEfC2Nsglly8TUQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_s6LlkU1oEfC2Nsglly8TUQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_s6Llkk1oEfC2Nsglly8TUQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_s6Llk01oEfC2Nsglly8TUQ" target="_s6LlJk1oEfC2Nsglly8TUQ" source="_s6Lk501oEfC2Nsglly8TUQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_s6LllE1oEfC2Nsglly8TUQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_s6LllU1oEfC2Nsglly8TUQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_s6Lllk1oEfC2Nsglly8TUQ" target="_s6LlR01oEfC2Nsglly8TUQ" source="_s6LlJk1oEfC2Nsglly8TUQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_s6Lll01oEfC2Nsglly8TUQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_s6LlmE1oEfC2Nsglly8TUQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_s6LlmU1oEfC2Nsglly8TUQ" target="_s6Llek1oEfC2Nsglly8TUQ" source="_s6Lldk1oEfC2Nsglly8TUQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_s6Llmk1oEfC2Nsglly8TUQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_s6Llm01oEfC2Nsglly8TUQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_s6LlnE1oEfC2Nsglly8TUQ" target="_s6LlCE1oEfC2Nsglly8TUQ" source="_s6LlJk1oEfC2Nsglly8TUQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_s6LlnU1oEfC2Nsglly8TUQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_s6Llnk1oEfC2Nsglly8TUQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_s6Lln01oEfC2Nsglly8TUQ" target="_s6Lldk1oEfC2Nsglly8TUQ" source="_s6LlR01oEfC2Nsglly8TUQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_s6LloE1oEfC2Nsglly8TUQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_s6LloU1oEfC2Nsglly8TUQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_s6Llok1oEfC2Nsglly8TUQ" target="_s6Lldk1oEfC2Nsglly8TUQ" source="_s6LlCE1oEfC2Nsglly8TUQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_s6Llo01oEfC2Nsglly8TUQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_s6LlpE1oEfC2Nsglly8TUQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_s6LlpU1oEfC2Nsglly8TUQ" name="Non" target="_s6LlKk1oEfC2Nsglly8TUQ" source="_s6Llek1oEfC2Nsglly8TUQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_s6Llpk1oEfC2Nsglly8TUQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_s6Llp01oEfC2Nsglly8TUQ" name="decisionManager != decisionRH" content="decisionManager != decisionRH" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_s6LlqE1oEfC2Nsglly8TUQ" name="Oui" target="_s6LlZU1oEfC2Nsglly8TUQ" source="_s6Llek1oEfC2Nsglly8TUQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_s6LlqU1oEfC2Nsglly8TUQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_s6Llqk1oEfC2Nsglly8TUQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_s6Llq01oEfC2Nsglly8TUQ" target="_s6LlZU1oEfC2Nsglly8TUQ" source="_s6LlKk1oEfC2Nsglly8TUQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_s6LlrE1oEfC2Nsglly8TUQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_s6LlrU1oEfC2Nsglly8TUQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_s6Llrk1oEfC2Nsglly8TUQ" documentation="Employé demandant une mission" name="Collaborateur" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_s6Llr01oEfC2Nsglly8TUQ" documentation="Manager validant les demandes" name="Manager"/>
      <actors xmi:type="process:Actor" xmi:id="_s6LlsE1oEfC2Nsglly8TUQ" documentation="Service RH pour validation finale" name="ServiceRH"/>
      <configurations xmi:type="configuration:Configuration" xmi:id="_s6LlsU1oEfC2Nsglly8TUQ" name="Qualification" version="8" username="walter.bates">
        <actorMappings xmi:type="actormapping:ActorMappingsType" xmi:id="_s6Llsk1oEfC2Nsglly8TUQ">
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_s6Lls01oEfC2Nsglly8TUQ" name="Collaborateur">
            <groups xmi:type="actormapping:Groups" xmi:id="_s6LltE1oEfC2Nsglly8TUQ"/>
            <memberships xmi:type="actormapping:Membership" xmi:id="_s6LltU1oEfC2Nsglly8TUQ"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_s6Lltk1oEfC2Nsglly8TUQ">
              <role>collaborateur</role>
            </roles>
            <users xmi:type="actormapping:Users" xmi:id="_s6Llt01oEfC2Nsglly8TUQ">
              <user>walter.bates</user>
            </users>
          </actorMapping>
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_s6LluE1oEfC2Nsglly8TUQ" name="Manager">
            <groups xmi:type="actormapping:Groups" xmi:id="_s6LluU1oEfC2Nsglly8TUQ"/>
            <memberships xmi:type="actormapping:Membership" xmi:id="_s6Lluk1oEfC2Nsglly8TUQ"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_s6Llu01oEfC2Nsglly8TUQ">
              <role>manager</role>
            </roles>
            <users xmi:type="actormapping:Users" xmi:id="_s6LlvE1oEfC2Nsglly8TUQ">
              <user>manager-test</user>
            </users>
          </actorMapping>
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_s6LlvU1oEfC2Nsglly8TUQ" name="ServiceRH">
            <groups xmi:type="actormapping:Groups" xmi:id="_s6Llvk1oEfC2Nsglly8TUQ"/>
            <memberships xmi:type="actormapping:Membership" xmi:id="_s6Llv01oEfC2Nsglly8TUQ"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_s6LlwE1oEfC2Nsglly8TUQ">
              <role>gestionnaire-rh</role>
            </roles>
            <users xmi:type="actormapping:Users" xmi:id="_s6LlwU1oEfC2Nsglly8TUQ">
              <user>andre.lejardinier</user>
              <user>walter.bates</user>
            </users>
          </actorMapping>
        </actorMappings>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_s6Llwk1oEfC2Nsglly8TUQ" id="CONNECTOR"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_s6Llw01oEfC2Nsglly8TUQ" id="GROOVY_SCRIPT"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_s6LlxE1oEfC2Nsglly8TUQ" id="ACTOR_FILTER"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_s6LlxU1oEfC2Nsglly8TUQ" id="OTHER"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_s6Llxk1oEfC2Nsglly8TUQ" id="GROOVY_SCRIPT"/>
      </configurations>
      <contract xmi:type="process:Contract" xmi:id="_s6Llx01oEfC2Nsglly8TUQ"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_s6LlyE1oEfC2Nsglly8TUQ">
        <name xmi:type="expression:Expression" xmi:id="_s6LlyU1oEfC2Nsglly8TUQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_s6Llyk1oEfC2Nsglly8TUQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_s6Lly01oEfC2Nsglly8TUQ">
        <name xmi:type="expression:Expression" xmi:id="_s6LlzE1oEfC2Nsglly8TUQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_s6LlzU1oEfC2Nsglly8TUQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_s6Llzk1oEfC2Nsglly8TUQ">
        <name xmi:type="expression:Expression" xmi:id="_s6Llz01oEfC2Nsglly8TUQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_s6Ll0E1oEfC2Nsglly8TUQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_s6Ll0U1oEfC2Nsglly8TUQ">
        <name xmi:type="expression:Expression" xmi:id="_s6Ll0k1oEfC2Nsglly8TUQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_s6Ll001oEfC2Nsglly8TUQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_s6Ll1E1oEfC2Nsglly8TUQ">
        <name xmi:type="expression:Expression" xmi:id="_s6Ll1U1oEfC2Nsglly8TUQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_s6Ll1k1oEfC2Nsglly8TUQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_s6Ll101oEfC2Nsglly8TUQ" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_s6Ll2E1oEfC2Nsglly8TUQ" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_s6Ll2U1oEfC2Nsglly8TUQ" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_s6Ll2k1oEfC2Nsglly8TUQ" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_s6Ll201oEfC2Nsglly8TUQ" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_s6Ll3E1oEfC2Nsglly8TUQ" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_s6Ll3U1oEfC2Nsglly8TUQ" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_s6Ll3k1oEfC2Nsglly8TUQ" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_s6Ll301oEfC2Nsglly8TUQ" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_s6Ll4E1oEfC2Nsglly8TUQ" type="Process" element="_s6Lk4E1oEfC2Nsglly8TUQ" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_s6Ll4U1oEfC2Nsglly8TUQ" type="2007" element="_s6Lk4U1oEfC2Nsglly8TUQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_s6Ll4k1oEfC2Nsglly8TUQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_s6Ll401oEfC2Nsglly8TUQ" type="7001">
        <children xmi:type="notation:Node" xmi:id="_s6Ll5E1oEfC2Nsglly8TUQ" type="3007" element="_s6Lk4k1oEfC2Nsglly8TUQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_s6Ll5U1oEfC2Nsglly8TUQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_s6Ll5k1oEfC2Nsglly8TUQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_s6Ll501oEfC2Nsglly8TUQ" type="3005" element="_s6Lk501oEfC2Nsglly8TUQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_s6Ll6E1oEfC2Nsglly8TUQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_s6Ll6U1oEfC2Nsglly8TUQ" x="156" y="27" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_s6Ll6k1oEfC2Nsglly8TUQ" type="3002" element="_s6Lk401oEfC2Nsglly8TUQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_s6Ll601oEfC2Nsglly8TUQ" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_s6Ll7E1oEfC2Nsglly8TUQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_s6Ll7U1oEfC2Nsglly8TUQ" x="60" y="39"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_s6Ll7k1oEfC2Nsglly8TUQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_s6Ll701oEfC2Nsglly8TUQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_s6Ll8E1oEfC2Nsglly8TUQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_s6Ll8U1oEfC2Nsglly8TUQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_s6Ll8k1oEfC2Nsglly8TUQ" x="48" y="10" width="1147" height="250"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_s6Ll801oEfC2Nsglly8TUQ" type="3007" element="_s6LlB01oEfC2Nsglly8TUQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_s6Ll9E1oEfC2Nsglly8TUQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_s6Ll9U1oEfC2Nsglly8TUQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_s6Ll9k1oEfC2Nsglly8TUQ" type="3005" element="_s6LlCE1oEfC2Nsglly8TUQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_s6Ll901oEfC2Nsglly8TUQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_s6Ll-E1oEfC2Nsglly8TUQ" x="327" y="24" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_s6Ll-U1oEfC2Nsglly8TUQ" type="3009" element="_s6LlJk1oEfC2Nsglly8TUQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_s6Ll-k1oEfC2Nsglly8TUQ" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_s6Ll-01oEfC2Nsglly8TUQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_s6Ll_E1oEfC2Nsglly8TUQ" x="175" y="32"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_s6Ll_U1oEfC2Nsglly8TUQ" type="3005" element="_s6LlKk1oEfC2Nsglly8TUQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_s6Ll_k1oEfC2Nsglly8TUQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_s6Ll_01oEfC2Nsglly8TUQ" x="642" y="32" width="120" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_s6LmAE1oEfC2Nsglly8TUQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_s6LmAU1oEfC2Nsglly8TUQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_s6LmAk1oEfC2Nsglly8TUQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_s6LmA01oEfC2Nsglly8TUQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_s6LmBE1oEfC2Nsglly8TUQ" x="48" y="250" width="1147" height="152"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_s6LmBU1oEfC2Nsglly8TUQ" type="3007" element="_s6LlRk1oEfC2Nsglly8TUQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_s6LmBk1oEfC2Nsglly8TUQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_s6LmB01oEfC2Nsglly8TUQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_s6LmCE1oEfC2Nsglly8TUQ" type="3005" element="_s6LlR01oEfC2Nsglly8TUQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_s6LmCU1oEfC2Nsglly8TUQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_s6LmCk1oEfC2Nsglly8TUQ" x="80" y="38" width="144" height="72"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_s6LmC01oEfC2Nsglly8TUQ" type="3027" element="_s6LlZU1oEfC2Nsglly8TUQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_s6LmDE1oEfC2Nsglly8TUQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_s6LmDU1oEfC2Nsglly8TUQ" x="930" y="19" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_s6LmDk1oEfC2Nsglly8TUQ" type="3009" element="_s6Lldk1oEfC2Nsglly8TUQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_s6LmD01oEfC2Nsglly8TUQ" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_s6LmEE1oEfC2Nsglly8TUQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_s6LmEU1oEfC2Nsglly8TUQ" x="471" y="109"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_s6LmEk1oEfC2Nsglly8TUQ" type="3008" element="_s6Llek1oEfC2Nsglly8TUQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_s6LmE01oEfC2Nsglly8TUQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_s6LmFE1oEfC2Nsglly8TUQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_s6LmFU1oEfC2Nsglly8TUQ" x="585" y="109"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_s6LmFk1oEfC2Nsglly8TUQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_s6LmF01oEfC2Nsglly8TUQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_s6LmGE1oEfC2Nsglly8TUQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_s6LmGU1oEfC2Nsglly8TUQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_s6LmGk1oEfC2Nsglly8TUQ" x="48" y="350" width="1147" height="214"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_s6LmG01oEfC2Nsglly8TUQ" type="3007" element="_s6Llfk1oEfC2Nsglly8TUQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_s6LmHE1oEfC2Nsglly8TUQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_s6LmHU1oEfC2Nsglly8TUQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_s6LmHk1oEfC2Nsglly8TUQ" type="3003" element="_s6Llf01oEfC2Nsglly8TUQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_s6LmH01oEfC2Nsglly8TUQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_s6LmIE1oEfC2Nsglly8TUQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_s6LmIU1oEfC2Nsglly8TUQ" x="1020" y="35"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_s6LmIk1oEfC2Nsglly8TUQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_s6LmI01oEfC2Nsglly8TUQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_s6LmJE1oEfC2Nsglly8TUQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_s6LmJU1oEfC2Nsglly8TUQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_s6LmJk1oEfC2Nsglly8TUQ" x="48" y="674" width="1147" height="100"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_s6LmJ01oEfC2Nsglly8TUQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_s6LmKE1oEfC2Nsglly8TUQ" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_s6LmKU1oEfC2Nsglly8TUQ"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_s6LmKk1oEfC2Nsglly8TUQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_s6LmK01oEfC2Nsglly8TUQ" width="1170" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_s6LmLE1oEfC2Nsglly8TUQ"/>
    <edges xmi:type="notation:Connector" xmi:id="_s6LmLU1oEfC2Nsglly8TUQ" type="4001" element="_s6LljU1oEfC2Nsglly8TUQ" source="_s6Ll6k1oEfC2Nsglly8TUQ" target="_s6Ll501oEfC2Nsglly8TUQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_s6LmLk1oEfC2Nsglly8TUQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_s6LmL01oEfC2Nsglly8TUQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_s6LmME1oEfC2Nsglly8TUQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_s6LmMU1oEfC2Nsglly8TUQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_s6LmMk1oEfC2Nsglly8TUQ" type="4001" element="_s6LlkE1oEfC2Nsglly8TUQ" source="_s6LmC01oEfC2Nsglly8TUQ" target="_s6LmHk1oEfC2Nsglly8TUQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_s6LmM01oEfC2Nsglly8TUQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_s6LmNE1oEfC2Nsglly8TUQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_s6LmNU1oEfC2Nsglly8TUQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_s6LmNk1oEfC2Nsglly8TUQ" points="[-61, 33, -33, -174]$[-61, 220, -33, 13]$[-30, 220, -2, 13]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_s6LmN01oEfC2Nsglly8TUQ" id="(1.0,0.45)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_s6LmOE1oEfC2Nsglly8TUQ" id="(0.06666666666666667,0.13333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_s6LmOU1oEfC2Nsglly8TUQ" type="4001" element="_s6Llk01oEfC2Nsglly8TUQ" source="_s6Ll501oEfC2Nsglly8TUQ" target="_s6Ll-U1oEfC2Nsglly8TUQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_s6LmOk1oEfC2Nsglly8TUQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_s6LmO01oEfC2Nsglly8TUQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_s6LmPE1oEfC2Nsglly8TUQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_s6LmPU1oEfC2Nsglly8TUQ" points="[0, 0, 83, -231]$[43, 0, 126, -231]$[43, 128, 126, -103]$[-81, 128, 2, -103]$[-81, 226, 2, -5]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_s6LmPk1oEfC2Nsglly8TUQ" id="(1.0,0.5)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_s6LmP01oEfC2Nsglly8TUQ" id="(0.4186046511627907,0.13953488372093023)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_s6LmQE1oEfC2Nsglly8TUQ" type="4001" element="_s6Lllk1oEfC2Nsglly8TUQ" source="_s6Ll-U1oEfC2Nsglly8TUQ" target="_s6LmCE1oEfC2Nsglly8TUQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_s6LmQU1oEfC2Nsglly8TUQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_s6LmQk1oEfC2Nsglly8TUQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_s6LmQ01oEfC2Nsglly8TUQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_s6LmRE1oEfC2Nsglly8TUQ" points="[-4, -6, 62, -148]$[92, -6, 158, -148]$[92, 46, 158, -96]$[-165, 46, -99, -96]$[-165, 160, -99, 18]$[-138, 160, -72, 18]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_s6LmRU1oEfC2Nsglly8TUQ" id="(1.0,0.7209302325581395)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_s6LmRk1oEfC2Nsglly8TUQ" type="4001" element="_s6LlmU1oEfC2Nsglly8TUQ" source="_s6LmDk1oEfC2Nsglly8TUQ" target="_s6LmEk1oEfC2Nsglly8TUQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_s6LmR01oEfC2Nsglly8TUQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_s6LmSE1oEfC2Nsglly8TUQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_s6LmSU1oEfC2Nsglly8TUQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_s6LmSk1oEfC2Nsglly8TUQ" points="[-1, -8, -74, 1]$[52, -8, -21, 1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_s6LmS01oEfC2Nsglly8TUQ" id="(1.0,0.6976744186046512)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_s6LmTE1oEfC2Nsglly8TUQ" type="4001" element="_s6LlnE1oEfC2Nsglly8TUQ" source="_s6Ll-U1oEfC2Nsglly8TUQ" target="_s6Ll9k1oEfC2Nsglly8TUQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_s6LmTU1oEfC2Nsglly8TUQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_s6LmTk1oEfC2Nsglly8TUQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_s6LmT01oEfC2Nsglly8TUQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_s6LmUE1oEfC2Nsglly8TUQ" points="[0, -7, -128, 0]$[109, -8, -19, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_s6LmUU1oEfC2Nsglly8TUQ" id="(1.0,0.6511627906976745)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_s6LmUk1oEfC2Nsglly8TUQ" id="(0.15833333333333333,0.48333333333333334)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_s6LmU01oEfC2Nsglly8TUQ" type="4001" element="_s6Lln01oEfC2Nsglly8TUQ" source="_s6LmCE1oEfC2Nsglly8TUQ" target="_s6LmDk1oEfC2Nsglly8TUQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_s6LmVE1oEfC2Nsglly8TUQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_s6LmVU1oEfC2Nsglly8TUQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_s6LmVk1oEfC2Nsglly8TUQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_s6LmV01oEfC2Nsglly8TUQ" points="[0, 0, -276, -51]$[255, 51, -21, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_s6LmWE1oEfC2Nsglly8TUQ" id="(1.0,0.3611111111111111)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_s6LmWU1oEfC2Nsglly8TUQ" type="4001" element="_s6Llok1oEfC2Nsglly8TUQ" source="_s6Ll9k1oEfC2Nsglly8TUQ" target="_s6LmDk1oEfC2Nsglly8TUQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_s6LmWk1oEfC2Nsglly8TUQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_s6LmW01oEfC2Nsglly8TUQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_s6LmXE1oEfC2Nsglly8TUQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_s6LmXU1oEfC2Nsglly8TUQ" points="[0, 7, -45, -203]$[43, 7, -2, -203]$[43, 191, -2, -19]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_s6LmXk1oEfC2Nsglly8TUQ" id="(1.0,0.45)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_s6LmX01oEfC2Nsglly8TUQ" type="4001" element="_s6LlpU1oEfC2Nsglly8TUQ" source="_s6LmEk1oEfC2Nsglly8TUQ" target="_s6Ll_U1oEfC2Nsglly8TUQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_s6LmYE1oEfC2Nsglly8TUQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_s6LmYU1oEfC2Nsglly8TUQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_s6LmYk1oEfC2Nsglly8TUQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_s6LmY01oEfC2Nsglly8TUQ" points="[-22, -32, -56, 208]$[-22, -231, -56, 9]$[14, -231, -20, 9]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_s6LmZE1oEfC2Nsglly8TUQ" id="(1.0,0.7441860465116279)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_s6LmZU1oEfC2Nsglly8TUQ" id="(0.16666666666666666,0.35)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_s6LmZk1oEfC2Nsglly8TUQ" type="4001" element="_s6LlqE1oEfC2Nsglly8TUQ" source="_s6LmEk1oEfC2Nsglly8TUQ" target="_s6LmC01oEfC2Nsglly8TUQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_s6LmZ01oEfC2Nsglly8TUQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_s6LmaE1oEfC2Nsglly8TUQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_s6LmaU1oEfC2Nsglly8TUQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_s6Lmak1oEfC2Nsglly8TUQ" points="[0, -8, -325, 83]$[90, -8, -235, 83]$[90, -85, -235, 6]$[302, -85, -23, 6]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_s6Lma01oEfC2Nsglly8TUQ" id="(1.0,0.6744186046511628)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_s6LmbE1oEfC2Nsglly8TUQ" id="(0.19166666666666668,0.4666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_s6LmbU1oEfC2Nsglly8TUQ" type="4001" element="_s6Llq01oEfC2Nsglly8TUQ" source="_s6Ll_U1oEfC2Nsglly8TUQ" target="_s6LmC01oEfC2Nsglly8TUQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_s6Lmbk1oEfC2Nsglly8TUQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_s6Lmb01oEfC2Nsglly8TUQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_s6LmcE1oEfC2Nsglly8TUQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_s6LmcU1oEfC2Nsglly8TUQ" points="[0, 0, -228, -143]$[222, 0, -6, -143]$[222, 113, -6, -30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_s6Lmck1oEfC2Nsglly8TUQ" id="(1.0,0.43333333333333335)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
