<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_E0B9oE1jEfCcZ9y8bwMp1w" name="V-3" bonitaModelVersion="8">
    <elements xmi:type="process:Pool" xmi:id="_E0B9oU1jEfCcZ9y8bwMp1w" name="V-3">
      <elements xmi:type="process:Lane" xmi:id="_E0B9ok1jEfCcZ9y8bwMp1w" name="Collaborateur" actor="_E0B-cE1jEfCcZ9y8bwMp1w">
        <elements xmi:type="process:StartEvent" xmi:id="_E0B9o01jEfCcZ9y8bwMp1w" name="Démarrer1" outgoing="_E0B-K01jEfCcZ9y8bwMp1w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_E0B9pE1jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_E0B9pU1jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_E0B9pk1jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_E0B9p01jEfCcZ9y8bwMp1w" name="Saisir demande de mission + Avance frais" outgoing="_E0B-Lk1jEfCcZ9y8bwMp1w" incoming="_E0B-K01jEfCcZ9y8bwMp1w" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_E0B9qE1jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_E0B9qU1jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_E0B9qk1jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_E0B9q01jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_E0B9rE1jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_E0B9rU1jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_E0B9rk1jEfCcZ9y8bwMp1w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_E0B9r01jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_E0B9sE1jEfCcZ9y8bwMp1w">
            <targetForm xmi:type="expression:Expression" xmi:id="_E0B9sU1jEfCcZ9y8bwMp1w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_E0B9sk1jEfCcZ9y8bwMp1w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_E0B9s01jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_Gl3SME1kEfCcZ9y8bwMp1w" name="Refus" outgoing="_fY_NkE1kEfCcZ9y8bwMp1w" incoming="_E0B-WE1jEfCcZ9y8bwMp1w _E0B-TE1jEfCcZ9y8bwMp1w _E0B-YU1jEfCcZ9y8bwMp1w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Gl35QU1kEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Gl35QE1kEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Gl35Qk1kEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_Hz-rIE1kEfCcZ9y8bwMp1w" name="Acceptation?" outgoing="_nLDbsE1kEfCcZ9y8bwMp1w _7NOwkE1kEfCcZ9y8bwMp1w" incoming="_fY_NkE1kEfCcZ9y8bwMp1w _v0nSgE1kEfCcZ9y8bwMp1w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Hz_SMU1kEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Hz_SME1kEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Hz_SMk1kEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_nLA_cE1kEfCcZ9y8bwMp1w" name="Fin1" incoming="_nLDbsE1kEfCcZ9y8bwMp1w _NDfngE1lEfCcZ9y8bwMp1w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_nLBmgU1kEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_nLBmgE1kEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_nLBmgk1kEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_7NNicE1kEfCcZ9y8bwMp1w" name="Collaborateur recoit le detaille de mission" outgoing="_CqiPok1lEfCcZ9y8bwMp1w _NDfngE1lEfCcZ9y8bwMp1w" incoming="_7NOwkE1kEfCcZ9y8bwMp1w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_7NOJgU1kEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_7NOJgE1kEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_7NOJgk1kEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_7NOJg01kEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_7NOJhE1kEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_7NOJhU1kEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_7NOJh01kEfCcZ9y8bwMp1w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_7NOJhk1kEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_CqhBgE1lEfCcZ9y8bwMp1w" name="confirme mission ?" outgoing="_J9ECEE1lEfCcZ9y8bwMp1w" incoming="_CqiPok1lEfCcZ9y8bwMp1w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_CqhokU1lEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_CqhokE1lEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Cqhokk1lEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_E0B9tE1jEfCcZ9y8bwMp1w" name="Manager">
        <elements xmi:type="process:Task" xmi:id="_E0B9tU1jEfCcZ9y8bwMp1w" name="Étudier la demande" outgoing="_E0B-T01jEfCcZ9y8bwMp1w" incoming="_E0B-N01jEfCcZ9y8bwMp1w _E0B-SU1jEfCcZ9y8bwMp1w" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_E0B9tk1jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_E0B9t01jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_E0B9uE1jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_E0B9uU1jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_E0B9uk1jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_E0B9u01jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_E0B9vE1jEfCcZ9y8bwMp1w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_E0B9vU1jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_E0B9vk1jEfCcZ9y8bwMp1w">
            <targetForm xmi:type="expression:Expression" xmi:id="_E0B9v01jEfCcZ9y8bwMp1w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_E0B9wE1jEfCcZ9y8bwMp1w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_E0B9wU1jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_E0B9wk1jEfCcZ9y8bwMp1w" name="Réponses identiques ?" outgoing="_E0B-WE1jEfCcZ9y8bwMp1w _E0B-W01jEfCcZ9y8bwMp1w _E0B-Xk1jEfCcZ9y8bwMp1w" incoming="_E0B-T01jEfCcZ9y8bwMp1w _E0B-Uk1jEfCcZ9y8bwMp1w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_E0B9w01jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_E0B9xE1jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_E0B9xU1jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_E0B9xk1jEfCcZ9y8bwMp1w" name="Etudier a nouveaux le dossie" outgoing="_E0B-bU1jEfCcZ9y8bwMp1w" incoming="_E0B-Xk1jEfCcZ9y8bwMp1w" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_E0B9x01jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_E0B9yE1jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_E0B9yU1jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_E0B9yk1jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_E0B9y01jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_E0B9zE1jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_E0B9zU1jEfCcZ9y8bwMp1w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_E0B9zk1jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_E0B9z01jEfCcZ9y8bwMp1w">
            <targetForm xmi:type="expression:Expression" xmi:id="_E0B90E1jEfCcZ9y8bwMp1w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_E0B90U1jEfCcZ9y8bwMp1w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_E0B90k1jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_E0B9001jEfCcZ9y8bwMp1w" name="Acceptation?" outgoing="_E0B-YU1jEfCcZ9y8bwMp1w _E0B-ak1jEfCcZ9y8bwMp1w" incoming="_E0B-bU1jEfCcZ9y8bwMp1w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_E0B91E1jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_E0B91U1jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_E0B91k1jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_E0B9101jEfCcZ9y8bwMp1w" name="Service RH">
        <elements xmi:type="process:Task" xmi:id="_E0B92E1jEfCcZ9y8bwMp1w" name="Évaluer demande exceptionnelle&#xA;&#xA;" outgoing="_E0B-QE1jEfCcZ9y8bwMp1w" incoming="_E0B-PU1jEfCcZ9y8bwMp1w" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_E0B92U1jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_E0B92k1jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_E0B9201jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_E0B93E1jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_E0B93U1jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_E0B93k1jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_E0B9301jEfCcZ9y8bwMp1w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_E0B94E1jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_E0B94U1jEfCcZ9y8bwMp1w">
            <targetForm xmi:type="expression:Expression" xmi:id="_E0B94k1jEfCcZ9y8bwMp1w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_E0B9401jEfCcZ9y8bwMp1w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_E0B95E1jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_E0B95U1jEfCcZ9y8bwMp1w" name="Demande acceptable ?" outgoing="_E0B-Q01jEfCcZ9y8bwMp1w _E0B-TE1jEfCcZ9y8bwMp1w" incoming="_E0B-QE1jEfCcZ9y8bwMp1w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_E0B95k1jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_E0B9501jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_E0B96E1jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_E0B96U1jEfCcZ9y8bwMp1w" name="Oui Exception Accordée" outgoing="_E0B-Rk1jEfCcZ9y8bwMp1w _E0B-SU1jEfCcZ9y8bwMp1w" incoming="_E0B-Q01jEfCcZ9y8bwMp1w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_E0B96k1jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_E0B9601jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_E0B97E1jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_E0B97U1jEfCcZ9y8bwMp1w" name="Analyser l'oportunité" outgoing="_E0B-Uk1jEfCcZ9y8bwMp1w" incoming="_E0B-Ok1jEfCcZ9y8bwMp1w _E0B-Rk1jEfCcZ9y8bwMp1w" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_E0B97k1jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_E0B9701jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_E0B98E1jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_E0B98U1jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_E0B98k1jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_E0B9801jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_E0B99E1jEfCcZ9y8bwMp1w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_E0B99U1jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_E0B99k1jEfCcZ9y8bwMp1w">
            <targetForm xmi:type="expression:Expression" xmi:id="_E0B9901jEfCcZ9y8bwMp1w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_E0B9-E1jEfCcZ9y8bwMp1w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_E0B9-U1jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_E0B-A01jEfCcZ9y8bwMp1w" name="Systéme">
        <elements xmi:type="process:ServiceTask" xmi:id="_E0B-BE1jEfCcZ9y8bwMp1w" name="Vérifier solde jours mission&#xA;&#xA;" outgoing="_E0B-MU1jEfCcZ9y8bwMp1w" incoming="_E0B-Lk1jEfCcZ9y8bwMp1w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_E0B-BU1jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_E0B-Bk1jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_E0B-B01jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_E0B-CE1jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_E0B-CU1jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_E0B-Ck1jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_E0B-C01jEfCcZ9y8bwMp1w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_E0B-DE1jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_E0B-DU1jEfCcZ9y8bwMp1w" name="Nombre de jours suffisant ?&#xA;&#xA;" outgoing="_E0B-NE1jEfCcZ9y8bwMp1w _E0B-PU1jEfCcZ9y8bwMp1w" incoming="_E0B-MU1jEfCcZ9y8bwMp1w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_E0B-Dk1jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_E0B-D01jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_E0B-EE1jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_E0B-EU1jEfCcZ9y8bwMp1w" name="OUI≥ jours requis" outgoing="_E0B-N01jEfCcZ9y8bwMp1w _E0B-Ok1jEfCcZ9y8bwMp1w" incoming="_E0B-NE1jEfCcZ9y8bwMp1w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_E0B-Ek1jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_E0B-E01jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_E0B-FE1jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_E0B-FU1jEfCcZ9y8bwMp1w" name="Déduire jour de solde" outgoing="_OaRNME1lEfCcZ9y8bwMp1w" incoming="_J9ECEE1lEfCcZ9y8bwMp1w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_E0B-Fk1jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_E0B-F01jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_E0B-GE1jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_E0B-GU1jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_E0B-Gk1jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_E0B-G01jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_E0B-HE1jEfCcZ9y8bwMp1w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_E0B-HU1jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_jyKCsE1jEfCcZ9y8bwMp1w" name="Calculer taux de change du jour" outgoing="_no_KUE1jEfCcZ9y8bwMp1w" incoming="_XfoEoE1kEfCcZ9y8bwMp1w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_jyKCsk1jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_jyKCsU1jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_jyKCs01jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_jyKCtE1jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_jyKCtU1jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_jyKCtk1jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_jyKCuE1jEfCcZ9y8bwMp1w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_jyKCt01jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_no98ME1jEfCcZ9y8bwMp1w" name="Convertir en monnaie locale" outgoing="_3pmHMU1jEfCcZ9y8bwMp1w" incoming="_no_KUE1jEfCcZ9y8bwMp1w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_no-jQU1jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_no-jQE1jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_no-jQk1jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_no-jQ01jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_no-jRE1jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_no-jRU1jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_no-jR01jEfCcZ9y8bwMp1w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_no-jRk1jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_3plgIE1jEfCcZ9y8bwMp1w" name="Envoyer proposition au collaborateur" outgoing="_v0nSgE1kEfCcZ9y8bwMp1w" incoming="_3pmHMU1jEfCcZ9y8bwMp1w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_3plgIk1jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_3plgIU1jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_3plgI01jEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_3plgJE1jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_3plgJU1jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_3plgJk1jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_3plgKE1jEfCcZ9y8bwMp1w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_3plgJ01jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_UjRBME1kEfCcZ9y8bwMp1w" name="Acceptation" outgoing="_XfoEoE1kEfCcZ9y8bwMp1w" incoming="_E0B-ak1jEfCcZ9y8bwMp1w _E0B-W01jEfCcZ9y8bwMp1w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_UjRoQU1kEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_UjRoQE1kEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_UjRoQk1kEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_OaQmIE1lEfCcZ9y8bwMp1w" name="Fin2" incoming="_OaRNME1lEfCcZ9y8bwMp1w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_OaQmIk1lEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_OaQmIU1lEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_OaQmI01lEfCcZ9y8bwMp1w" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_E0B-J01jEfCcZ9y8bwMp1w">
        <targetForm xmi:type="expression:Expression" xmi:id="_E0B-KE1jEfCcZ9y8bwMp1w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_E0B-KU1jEfCcZ9y8bwMp1w">
        <targetForm xmi:type="expression:Expression" xmi:id="_E0B-Kk1jEfCcZ9y8bwMp1w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_E0B-K01jEfCcZ9y8bwMp1w" target="_E0B9p01jEfCcZ9y8bwMp1w" source="_E0B9o01jEfCcZ9y8bwMp1w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_E0B-LE1jEfCcZ9y8bwMp1w"/>
        <condition xmi:type="expression:Expression" xmi:id="_E0B-LU1jEfCcZ9y8bwMp1w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_E0B-Lk1jEfCcZ9y8bwMp1w" target="_E0B-BE1jEfCcZ9y8bwMp1w" source="_E0B9p01jEfCcZ9y8bwMp1w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_E0B-L01jEfCcZ9y8bwMp1w"/>
        <condition xmi:type="expression:Expression" xmi:id="_E0B-ME1jEfCcZ9y8bwMp1w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_E0B-MU1jEfCcZ9y8bwMp1w" target="_E0B-DU1jEfCcZ9y8bwMp1w" source="_E0B-BE1jEfCcZ9y8bwMp1w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_E0B-Mk1jEfCcZ9y8bwMp1w"/>
        <condition xmi:type="expression:Expression" xmi:id="_E0B-M01jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_E0B-NE1jEfCcZ9y8bwMp1w" target="_E0B-EU1jEfCcZ9y8bwMp1w" source="_E0B-DU1jEfCcZ9y8bwMp1w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_E0B-NU1jEfCcZ9y8bwMp1w"/>
        <condition xmi:type="expression:Expression" xmi:id="_E0B-Nk1jEfCcZ9y8bwMp1w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_E0B-N01jEfCcZ9y8bwMp1w" target="_E0B9tU1jEfCcZ9y8bwMp1w" source="_E0B-EU1jEfCcZ9y8bwMp1w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_E0B-OE1jEfCcZ9y8bwMp1w"/>
        <condition xmi:type="expression:Expression" xmi:id="_E0B-OU1jEfCcZ9y8bwMp1w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_E0B-Ok1jEfCcZ9y8bwMp1w" target="_E0B97U1jEfCcZ9y8bwMp1w" source="_E0B-EU1jEfCcZ9y8bwMp1w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_E0B-O01jEfCcZ9y8bwMp1w"/>
        <condition xmi:type="expression:Expression" xmi:id="_E0B-PE1jEfCcZ9y8bwMp1w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_E0B-PU1jEfCcZ9y8bwMp1w" name="Non&lt;= jours requis" target="_E0B92E1jEfCcZ9y8bwMp1w" source="_E0B-DU1jEfCcZ9y8bwMp1w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_E0B-Pk1jEfCcZ9y8bwMp1w"/>
        <condition xmi:type="expression:Expression" xmi:id="_E0B-P01jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_E0B-QE1jEfCcZ9y8bwMp1w" target="_E0B95U1jEfCcZ9y8bwMp1w" source="_E0B92E1jEfCcZ9y8bwMp1w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_E0B-QU1jEfCcZ9y8bwMp1w"/>
        <condition xmi:type="expression:Expression" xmi:id="_E0B-Qk1jEfCcZ9y8bwMp1w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_E0B-Q01jEfCcZ9y8bwMp1w" target="_E0B96U1jEfCcZ9y8bwMp1w" source="_E0B95U1jEfCcZ9y8bwMp1w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_E0B-RE1jEfCcZ9y8bwMp1w"/>
        <condition xmi:type="expression:Expression" xmi:id="_E0B-RU1jEfCcZ9y8bwMp1w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_E0B-Rk1jEfCcZ9y8bwMp1w" target="_E0B97U1jEfCcZ9y8bwMp1w" source="_E0B96U1jEfCcZ9y8bwMp1w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_E0B-R01jEfCcZ9y8bwMp1w"/>
        <condition xmi:type="expression:Expression" xmi:id="_E0B-SE1jEfCcZ9y8bwMp1w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_E0B-SU1jEfCcZ9y8bwMp1w" target="_E0B9tU1jEfCcZ9y8bwMp1w" source="_E0B96U1jEfCcZ9y8bwMp1w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_E0B-Sk1jEfCcZ9y8bwMp1w"/>
        <condition xmi:type="expression:Expression" xmi:id="_E0B-S01jEfCcZ9y8bwMp1w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_E0B-TE1jEfCcZ9y8bwMp1w" name="Refus pour manque de jour" target="_Gl3SME1kEfCcZ9y8bwMp1w" source="_E0B95U1jEfCcZ9y8bwMp1w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_E0B-TU1jEfCcZ9y8bwMp1w"/>
        <condition xmi:type="expression:Expression" xmi:id="_E0B-Tk1jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_E0B-T01jEfCcZ9y8bwMp1w" target="_E0B9wk1jEfCcZ9y8bwMp1w" source="_E0B9tU1jEfCcZ9y8bwMp1w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_E0B-UE1jEfCcZ9y8bwMp1w"/>
        <condition xmi:type="expression:Expression" xmi:id="_E0B-UU1jEfCcZ9y8bwMp1w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_E0B-Uk1jEfCcZ9y8bwMp1w" target="_E0B9wk1jEfCcZ9y8bwMp1w" source="_E0B97U1jEfCcZ9y8bwMp1w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_E0B-U01jEfCcZ9y8bwMp1w"/>
        <condition xmi:type="expression:Expression" xmi:id="_E0B-VE1jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_E0B-WE1jEfCcZ9y8bwMp1w" name="Oui Refus" target="_Gl3SME1kEfCcZ9y8bwMp1w" source="_E0B9wk1jEfCcZ9y8bwMp1w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_E0B-WU1jEfCcZ9y8bwMp1w"/>
        <condition xmi:type="expression:Expression" xmi:id="_E0B-Wk1jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_E0B-W01jEfCcZ9y8bwMp1w" name="Oui Accord" target="_UjRBME1kEfCcZ9y8bwMp1w" source="_E0B9wk1jEfCcZ9y8bwMp1w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_E0B-XE1jEfCcZ9y8bwMp1w"/>
        <condition xmi:type="expression:Expression" xmi:id="_E0B-XU1jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_E0B-Xk1jEfCcZ9y8bwMp1w" name="OUI /Non" target="_E0B9xk1jEfCcZ9y8bwMp1w" source="_E0B9wk1jEfCcZ9y8bwMp1w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_E0B-X01jEfCcZ9y8bwMp1w"/>
        <condition xmi:type="expression:Expression" xmi:id="_E0B-YE1jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_E0B-YU1jEfCcZ9y8bwMp1w" name="Non Refus" target="_Gl3SME1kEfCcZ9y8bwMp1w" source="_E0B9001jEfCcZ9y8bwMp1w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_E0B-Yk1jEfCcZ9y8bwMp1w"/>
        <condition xmi:type="expression:Expression" xmi:id="_E0B-Y01jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_E0B-ak1jEfCcZ9y8bwMp1w" name="Oui Acceptation" target="_UjRBME1kEfCcZ9y8bwMp1w" source="_E0B9001jEfCcZ9y8bwMp1w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_E0B-a01jEfCcZ9y8bwMp1w"/>
        <condition xmi:type="expression:Expression" xmi:id="_E0B-bE1jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_E0B-bU1jEfCcZ9y8bwMp1w" target="_E0B9001jEfCcZ9y8bwMp1w" source="_E0B9xk1jEfCcZ9y8bwMp1w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_E0B-bk1jEfCcZ9y8bwMp1w"/>
        <condition xmi:type="expression:Expression" xmi:id="_E0B-b01jEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_no_KUE1jEfCcZ9y8bwMp1w" target="_no98ME1jEfCcZ9y8bwMp1w" source="_jyKCsE1jEfCcZ9y8bwMp1w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_no_KUU1jEfCcZ9y8bwMp1w"/>
        <condition xmi:type="expression:Expression" xmi:id="_no_KUk1jEfCcZ9y8bwMp1w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_3pmHMU1jEfCcZ9y8bwMp1w" target="_3plgIE1jEfCcZ9y8bwMp1w" source="_no98ME1jEfCcZ9y8bwMp1w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_3pmHMk1jEfCcZ9y8bwMp1w"/>
        <condition xmi:type="expression:Expression" xmi:id="_3pmHM01jEfCcZ9y8bwMp1w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_XfoEoE1kEfCcZ9y8bwMp1w" target="_jyKCsE1jEfCcZ9y8bwMp1w" source="_UjRBME1kEfCcZ9y8bwMp1w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_XfoEoU1kEfCcZ9y8bwMp1w"/>
        <condition xmi:type="expression:Expression" xmi:id="_XfoEok1kEfCcZ9y8bwMp1w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_fY_NkE1kEfCcZ9y8bwMp1w" name="Refus" target="_Hz-rIE1kEfCcZ9y8bwMp1w" source="_Gl3SME1kEfCcZ9y8bwMp1w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_fY_NkU1kEfCcZ9y8bwMp1w"/>
        <condition xmi:type="expression:Expression" xmi:id="_fY_Nkk1kEfCcZ9y8bwMp1w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_nLDbsE1kEfCcZ9y8bwMp1w" name="Non" target="_nLA_cE1kEfCcZ9y8bwMp1w" source="_Hz-rIE1kEfCcZ9y8bwMp1w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_nLDbsU1kEfCcZ9y8bwMp1w"/>
        <condition xmi:type="expression:Expression" xmi:id="_nLECwE1kEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_v0nSgE1kEfCcZ9y8bwMp1w" name="Acceptation" target="_Hz-rIE1kEfCcZ9y8bwMp1w" source="_3plgIE1jEfCcZ9y8bwMp1w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_v0n5kE1kEfCcZ9y8bwMp1w"/>
        <condition xmi:type="expression:Expression" xmi:id="_v0n5kU1kEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_7NOwkE1kEfCcZ9y8bwMp1w" target="_7NNicE1kEfCcZ9y8bwMp1w" source="_Hz-rIE1kEfCcZ9y8bwMp1w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_7NOwkU1kEfCcZ9y8bwMp1w"/>
        <condition xmi:type="expression:Expression" xmi:id="_7NOwkk1kEfCcZ9y8bwMp1w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_CqiPok1lEfCcZ9y8bwMp1w" target="_CqhBgE1lEfCcZ9y8bwMp1w" source="_7NNicE1kEfCcZ9y8bwMp1w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Cqi2sE1lEfCcZ9y8bwMp1w"/>
        <condition xmi:type="expression:Expression" xmi:id="_Cqi2sU1lEfCcZ9y8bwMp1w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_J9ECEE1lEfCcZ9y8bwMp1w" name="Accepte" target="_E0B-FU1jEfCcZ9y8bwMp1w" source="_CqhBgE1lEfCcZ9y8bwMp1w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_J9ECEU1lEfCcZ9y8bwMp1w"/>
        <condition xmi:type="expression:Expression" xmi:id="_J9ECEk1lEfCcZ9y8bwMp1w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_NDfngE1lEfCcZ9y8bwMp1w" name="Non" target="_nLA_cE1kEfCcZ9y8bwMp1w" source="_7NNicE1kEfCcZ9y8bwMp1w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_NDfngU1lEfCcZ9y8bwMp1w"/>
        <condition xmi:type="expression:Expression" xmi:id="_NDfngk1lEfCcZ9y8bwMp1w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_OaRNME1lEfCcZ9y8bwMp1w" target="_OaQmIE1lEfCcZ9y8bwMp1w" source="_E0B-FU1jEfCcZ9y8bwMp1w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_OaRNMU1lEfCcZ9y8bwMp1w"/>
        <condition xmi:type="expression:Expression" xmi:id="_OaRNMk1lEfCcZ9y8bwMp1w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_E0B-cE1jEfCcZ9y8bwMp1w" documentation="Ceci est un exemple d'acteur associé à tous les utilisateurs d'ACME" name="Employee actor" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_E0B-cU1jEfCcZ9y8bwMp1w"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_E0B-ck1jEfCcZ9y8bwMp1w">
        <name xmi:type="expression:Expression" xmi:id="_E0B-c01jEfCcZ9y8bwMp1w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_E0B-dE1jEfCcZ9y8bwMp1w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_E0B-dU1jEfCcZ9y8bwMp1w">
        <name xmi:type="expression:Expression" xmi:id="_E0B-dk1jEfCcZ9y8bwMp1w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_E0B-d01jEfCcZ9y8bwMp1w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_E0B-eE1jEfCcZ9y8bwMp1w">
        <name xmi:type="expression:Expression" xmi:id="_E0B-eU1jEfCcZ9y8bwMp1w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_E0B-ek1jEfCcZ9y8bwMp1w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_E0B-e01jEfCcZ9y8bwMp1w">
        <name xmi:type="expression:Expression" xmi:id="_E0B-fE1jEfCcZ9y8bwMp1w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_E0B-fU1jEfCcZ9y8bwMp1w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_E0B-fk1jEfCcZ9y8bwMp1w">
        <name xmi:type="expression:Expression" xmi:id="_E0B-f01jEfCcZ9y8bwMp1w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_E0B-gE1jEfCcZ9y8bwMp1w" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_E0B-gU1jEfCcZ9y8bwMp1w" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_E0B-gk1jEfCcZ9y8bwMp1w" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_E0B-g01jEfCcZ9y8bwMp1w" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_E0B-hE1jEfCcZ9y8bwMp1w" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_E0B-hU1jEfCcZ9y8bwMp1w" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_E0B-hk1jEfCcZ9y8bwMp1w" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_E0B-h01jEfCcZ9y8bwMp1w" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_E0B-iE1jEfCcZ9y8bwMp1w" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_E0B-iU1jEfCcZ9y8bwMp1w" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_E0B-ik1jEfCcZ9y8bwMp1w" type="Process" element="_E0B9oE1jEfCcZ9y8bwMp1w" name="MonDiagramme" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_E0B-i01jEfCcZ9y8bwMp1w" type="2007" element="_E0B9oU1jEfCcZ9y8bwMp1w">
      <children xmi:type="notation:DecorationNode" xmi:id="_E0B-jE1jEfCcZ9y8bwMp1w" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_E0B-jU1jEfCcZ9y8bwMp1w" type="7001">
        <children xmi:type="notation:Node" xmi:id="_E0B-jk1jEfCcZ9y8bwMp1w" type="3007" element="_E0B9ok1jEfCcZ9y8bwMp1w">
          <children xmi:type="notation:DecorationNode" xmi:id="_E0B-j01jEfCcZ9y8bwMp1w" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_E0B-kE1jEfCcZ9y8bwMp1w" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_E0B-kU1jEfCcZ9y8bwMp1w" type="3005" element="_E0B9p01jEfCcZ9y8bwMp1w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_E0B-kk1jEfCcZ9y8bwMp1w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_E0B-k01jEfCcZ9y8bwMp1w" x="160" y="60" width="198" height="99"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_E0B-lE1jEfCcZ9y8bwMp1w" type="3002" element="_E0B9o01jEfCcZ9y8bwMp1w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_E0B-lU1jEfCcZ9y8bwMp1w" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_E0B-lk1jEfCcZ9y8bwMp1w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_E0B-l01jEfCcZ9y8bwMp1w" x="60" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Gl4gUE1kEfCcZ9y8bwMp1w" type="3009" element="_Gl3SME1kEfCcZ9y8bwMp1w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_Gl4gUk1kEfCcZ9y8bwMp1w" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Gl4gU01kEfCcZ9y8bwMp1w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Gl4gUU1kEfCcZ9y8bwMp1w" x="1729" y="62"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_H0AgUE1kEfCcZ9y8bwMp1w" type="3008" element="_Hz-rIE1kEfCcZ9y8bwMp1w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_H0AgUk1kEfCcZ9y8bwMp1w" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_H0AgU01kEfCcZ9y8bwMp1w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_H0AgUU1kEfCcZ9y8bwMp1w" x="1910" y="104"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_nLCNkE1kEfCcZ9y8bwMp1w" type="3003" element="_nLA_cE1kEfCcZ9y8bwMp1w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_nLC0oE1kEfCcZ9y8bwMp1w" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_nLC0oU1kEfCcZ9y8bwMp1w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_nLCNkU1kEfCcZ9y8bwMp1w" x="2205" y="30"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_7NOJiE1kEfCcZ9y8bwMp1w" type="3027" element="_7NNicE1kEfCcZ9y8bwMp1w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_7NOJik1kEfCcZ9y8bwMp1w" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_7NOJiU1kEfCcZ9y8bwMp1w" x="2007" y="158" width="144" height="72"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Cqhok01lEfCcZ9y8bwMp1w" type="3009" element="_CqhBgE1lEfCcZ9y8bwMp1w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_CqiPoE1lEfCcZ9y8bwMp1w" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_CqiPoU1lEfCcZ9y8bwMp1w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_CqholE1lEfCcZ9y8bwMp1w" x="2242" y="162"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_E0B-mE1jEfCcZ9y8bwMp1w"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_E0B-mU1jEfCcZ9y8bwMp1w" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_E0B-mk1jEfCcZ9y8bwMp1w"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_E0B-m01jEfCcZ9y8bwMp1w"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_E0B-nE1jEfCcZ9y8bwMp1w" x="58" y="10" width="2937" height="295"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_E0B-nU1jEfCcZ9y8bwMp1w" type="3007" element="_E0B9tE1jEfCcZ9y8bwMp1w">
          <children xmi:type="notation:DecorationNode" xmi:id="_E0B-nk1jEfCcZ9y8bwMp1w" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_E0B-n01jEfCcZ9y8bwMp1w" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_E0B-oE1jEfCcZ9y8bwMp1w" type="3005" element="_E0B9tU1jEfCcZ9y8bwMp1w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_E0B-oU1jEfCcZ9y8bwMp1w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_E0B-ok1jEfCcZ9y8bwMp1w" x="609" y="30" width="188" height="94"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_E0B-o01jEfCcZ9y8bwMp1w" type="3008" element="_E0B9wk1jEfCcZ9y8bwMp1w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_E0B-pE1jEfCcZ9y8bwMp1w" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_E0B-pU1jEfCcZ9y8bwMp1w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_E0B-pk1jEfCcZ9y8bwMp1w" x="1085" y="70" width="42" height="42"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_E0B-p01jEfCcZ9y8bwMp1w" type="3005" element="_E0B9xk1jEfCcZ9y8bwMp1w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_E0B-qE1jEfCcZ9y8bwMp1w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_E0B-qU1jEfCcZ9y8bwMp1w" x="1507" y="10" width="125" height="62"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_E0B-qk1jEfCcZ9y8bwMp1w" type="3008" element="_E0B9001jEfCcZ9y8bwMp1w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_E0B-q01jEfCcZ9y8bwMp1w" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_E0B-rE1jEfCcZ9y8bwMp1w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_E0B-rU1jEfCcZ9y8bwMp1w" x="1561" y="103"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_E0B-rk1jEfCcZ9y8bwMp1w"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_E0B-r01jEfCcZ9y8bwMp1w" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_E0B-sE1jEfCcZ9y8bwMp1w"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_E0B-sU1jEfCcZ9y8bwMp1w"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_E0B-sk1jEfCcZ9y8bwMp1w" x="194" y="176"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_E0B-s01jEfCcZ9y8bwMp1w" type="3007" element="_E0B9101jEfCcZ9y8bwMp1w">
          <children xmi:type="notation:DecorationNode" xmi:id="_E0B-tE1jEfCcZ9y8bwMp1w" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_E0B-tU1jEfCcZ9y8bwMp1w" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_E0B-tk1jEfCcZ9y8bwMp1w" type="3005" element="_E0B92E1jEfCcZ9y8bwMp1w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_E0B-t01jEfCcZ9y8bwMp1w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_E0B-uE1jEfCcZ9y8bwMp1w" x="217" y="116" width="201" height="100"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_E0B-uU1jEfCcZ9y8bwMp1w" type="3008" element="_E0B95U1jEfCcZ9y8bwMp1w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_E0B-uk1jEfCcZ9y8bwMp1w" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_E0B-u01jEfCcZ9y8bwMp1w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_E0B-vE1jEfCcZ9y8bwMp1w" x="525" y="144" width="42" height="42"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_E0B-vU1jEfCcZ9y8bwMp1w" type="3009" element="_E0B96U1jEfCcZ9y8bwMp1w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_E0B-vk1jEfCcZ9y8bwMp1w" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_E0B-v01jEfCcZ9y8bwMp1w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_E0B-wE1jEfCcZ9y8bwMp1w" x="693" y="144"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_E0B-wU1jEfCcZ9y8bwMp1w" type="3005" element="_E0B97U1jEfCcZ9y8bwMp1w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_E0B-wk1jEfCcZ9y8bwMp1w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_E0B-w01jEfCcZ9y8bwMp1w" x="889" y="122" width="186" height="92"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_E0B-x01jEfCcZ9y8bwMp1w"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_E0B-yE1jEfCcZ9y8bwMp1w" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_E0B-yU1jEfCcZ9y8bwMp1w"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_E0B-yk1jEfCcZ9y8bwMp1w"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_E0B-y01jEfCcZ9y8bwMp1w" x="132" y="375"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_E0B-zE1jEfCcZ9y8bwMp1w" type="3007" element="_E0B-A01jEfCcZ9y8bwMp1w">
          <children xmi:type="notation:DecorationNode" xmi:id="_E0B-zU1jEfCcZ9y8bwMp1w" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_E0B-zk1jEfCcZ9y8bwMp1w" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_E0B-z01jEfCcZ9y8bwMp1w" type="3027" element="_E0B-BE1jEfCcZ9y8bwMp1w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_E0B-0E1jEfCcZ9y8bwMp1w" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_E0B-0U1jEfCcZ9y8bwMp1w" x="58" y="44" width="158" height="79"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_E0B-0k1jEfCcZ9y8bwMp1w" type="3008" element="_E0B-DU1jEfCcZ9y8bwMp1w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_E0B-001jEfCcZ9y8bwMp1w" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_E0B-1E1jEfCcZ9y8bwMp1w" x="8" y="25"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_E0B-1U1jEfCcZ9y8bwMp1w" x="301" y="62"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_E0B-1k1jEfCcZ9y8bwMp1w" type="3009" element="_E0B-EU1jEfCcZ9y8bwMp1w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_E0B-101jEfCcZ9y8bwMp1w" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_E0B-2E1jEfCcZ9y8bwMp1w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_E0B-2U1jEfCcZ9y8bwMp1w" x="461" y="54"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_E0B-2k1jEfCcZ9y8bwMp1w" type="3027" element="_E0B-FU1jEfCcZ9y8bwMp1w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_E0B-201jEfCcZ9y8bwMp1w" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_E0B-3E1jEfCcZ9y8bwMp1w" x="2115" y="87" width="160" height="80"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_jyLQ0E1jEfCcZ9y8bwMp1w" type="3027" element="_jyKCsE1jEfCcZ9y8bwMp1w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_jyLQ0k1jEfCcZ9y8bwMp1w" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jyLQ0U1jEfCcZ9y8bwMp1w" x="1309" y="155" width="126" height="63"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_no-jSE1jEfCcZ9y8bwMp1w" type="3027" element="_no98ME1jEfCcZ9y8bwMp1w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_no-jSk1jEfCcZ9y8bwMp1w" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_no-jSU1jEfCcZ9y8bwMp1w" x="1550" y="144" width="160" height="80"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_3plgKU1jEfCcZ9y8bwMp1w" type="3027" element="_3plgIE1jEfCcZ9y8bwMp1w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_3pmHME1jEfCcZ9y8bwMp1w" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_3plgKk1jEfCcZ9y8bwMp1w" x="1785" y="154" width="158" height="79"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_UjS2YE1kEfCcZ9y8bwMp1w" type="3009" element="_UjRBME1kEfCcZ9y8bwMp1w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_UjS2Yk1kEfCcZ9y8bwMp1w" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_UjTdcE1kEfCcZ9y8bwMp1w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_UjS2YU1kEfCcZ9y8bwMp1w" x="1365" y="54"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_OaQmJE1lEfCcZ9y8bwMp1w" type="3003" element="_OaQmIE1lEfCcZ9y8bwMp1w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_OaQmJk1lEfCcZ9y8bwMp1w" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_OaQmJ01lEfCcZ9y8bwMp1w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_OaQmJU1lEfCcZ9y8bwMp1w" x="2382" y="107"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_E0B-4E1jEfCcZ9y8bwMp1w"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_E0B-4U1jEfCcZ9y8bwMp1w" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_E0B-4k1jEfCcZ9y8bwMp1w"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_E0B-401jEfCcZ9y8bwMp1w"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_E0B-5E1jEfCcZ9y8bwMp1w" x="33" y="750" width="2937" height="291"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_E0B-5U1jEfCcZ9y8bwMp1w"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_E0B-5k1jEfCcZ9y8bwMp1w" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_E0B-501jEfCcZ9y8bwMp1w"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_E0B-6E1jEfCcZ9y8bwMp1w"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_E0B-6U1jEfCcZ9y8bwMp1w" width="2970" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_E0B-6k1jEfCcZ9y8bwMp1w"/>
    <edges xmi:type="notation:Connector" xmi:id="_E0B-601jEfCcZ9y8bwMp1w" type="4001" element="_E0B-K01jEfCcZ9y8bwMp1w" source="_E0B-lE1jEfCcZ9y8bwMp1w" target="_E0B-kU1jEfCcZ9y8bwMp1w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_E0B-7E1jEfCcZ9y8bwMp1w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_E0B-7U1jEfCcZ9y8bwMp1w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_E0B-7k1jEfCcZ9y8bwMp1w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_E0B-701jEfCcZ9y8bwMp1w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_E0B-8E1jEfCcZ9y8bwMp1w" type="4001" element="_E0B-Lk1jEfCcZ9y8bwMp1w" source="_E0B-kU1jEfCcZ9y8bwMp1w" target="_E0B-z01jEfCcZ9y8bwMp1w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_E0B-8U1jEfCcZ9y8bwMp1w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_E0B-8k1jEfCcZ9y8bwMp1w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_E0B-801jEfCcZ9y8bwMp1w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_E0B-9E1jEfCcZ9y8bwMp1w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_E0B-9U1jEfCcZ9y8bwMp1w" type="4001" element="_E0B-MU1jEfCcZ9y8bwMp1w" source="_E0B-z01jEfCcZ9y8bwMp1w" target="_E0B-0k1jEfCcZ9y8bwMp1w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_E0B-9k1jEfCcZ9y8bwMp1w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_E0B-901jEfCcZ9y8bwMp1w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_E0B--E1jEfCcZ9y8bwMp1w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_E0B--U1jEfCcZ9y8bwMp1w" points="[0, 6, -94, -7]$[94, -3, 0, -16]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_E0B--k1jEfCcZ9y8bwMp1w" id="(1.0,0.4177215189873418)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_E0B--01jEfCcZ9y8bwMp1w" type="4001" element="_E0B-NE1jEfCcZ9y8bwMp1w" source="_E0B-0k1jEfCcZ9y8bwMp1w" target="_E0B-1k1jEfCcZ9y8bwMp1w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_E0B-_E1jEfCcZ9y8bwMp1w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_E0B-_U1jEfCcZ9y8bwMp1w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_E0B-_k1jEfCcZ9y8bwMp1w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_E0B-_01jEfCcZ9y8bwMp1w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_E0B_AE1jEfCcZ9y8bwMp1w" type="4001" element="_E0B-N01jEfCcZ9y8bwMp1w" source="_E0B-1k1jEfCcZ9y8bwMp1w" target="_E0B-oE1jEfCcZ9y8bwMp1w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_E0B_AU1jEfCcZ9y8bwMp1w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_E0B_Ak1jEfCcZ9y8bwMp1w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_E0B_A01jEfCcZ9y8bwMp1w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_E0B_BE1jEfCcZ9y8bwMp1w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_E0B_BU1jEfCcZ9y8bwMp1w" type="4001" element="_E0B-Ok1jEfCcZ9y8bwMp1w" source="_E0B-1k1jEfCcZ9y8bwMp1w" target="_E0B-wU1jEfCcZ9y8bwMp1w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_E0B_Bk1jEfCcZ9y8bwMp1w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_E0B_B01jEfCcZ9y8bwMp1w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_E0B_CE1jEfCcZ9y8bwMp1w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_E0B_CU1jEfCcZ9y8bwMp1w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_E0B_Ck1jEfCcZ9y8bwMp1w" type="4001" element="_E0B-PU1jEfCcZ9y8bwMp1w" source="_E0B-0k1jEfCcZ9y8bwMp1w" target="_E0B-tk1jEfCcZ9y8bwMp1w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_E0B_C01jEfCcZ9y8bwMp1w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_E0B_DE1jEfCcZ9y8bwMp1w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_E0B_DU1jEfCcZ9y8bwMp1w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_E0B_Dk1jEfCcZ9y8bwMp1w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_E0B_D01jEfCcZ9y8bwMp1w" type="4001" element="_E0B-QE1jEfCcZ9y8bwMp1w" source="_E0B-tk1jEfCcZ9y8bwMp1w" target="_E0B-uU1jEfCcZ9y8bwMp1w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_E0B_EE1jEfCcZ9y8bwMp1w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_E0B_EU1jEfCcZ9y8bwMp1w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_E0B_Ek1jEfCcZ9y8bwMp1w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_E0B_E01jEfCcZ9y8bwMp1w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_E0B_FE1jEfCcZ9y8bwMp1w" type="4001" element="_E0B-Q01jEfCcZ9y8bwMp1w" source="_E0B-uU1jEfCcZ9y8bwMp1w" target="_E0B-vU1jEfCcZ9y8bwMp1w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_E0B_FU1jEfCcZ9y8bwMp1w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_E0B_Fk1jEfCcZ9y8bwMp1w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_E0B_F01jEfCcZ9y8bwMp1w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_E0B_GE1jEfCcZ9y8bwMp1w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_E0B_GU1jEfCcZ9y8bwMp1w" type="4001" element="_E0B-Rk1jEfCcZ9y8bwMp1w" source="_E0B-vU1jEfCcZ9y8bwMp1w" target="_E0B-wU1jEfCcZ9y8bwMp1w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_E0B_Gk1jEfCcZ9y8bwMp1w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_E0B_G01jEfCcZ9y8bwMp1w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_E0B_HE1jEfCcZ9y8bwMp1w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_E0B_HU1jEfCcZ9y8bwMp1w" points="[-5, 0, -93, 2]$[80, 17, -8, 19]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_E0B_Hk1jEfCcZ9y8bwMp1w" id="(1.0,0.6511627906976745)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_E0B_H01jEfCcZ9y8bwMp1w" type="4001" element="_E0B-SU1jEfCcZ9y8bwMp1w" source="_E0B-vU1jEfCcZ9y8bwMp1w" target="_E0B-oE1jEfCcZ9y8bwMp1w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_E0B_IE1jEfCcZ9y8bwMp1w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_E0B_IU1jEfCcZ9y8bwMp1w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_E0B_Ik1jEfCcZ9y8bwMp1w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_E0B_I01jEfCcZ9y8bwMp1w" points="[-23, -26, 114, 290]$[-23, -316, 114, 0]$[-43, -316, 94, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_E0B_JE1jEfCcZ9y8bwMp1w" id="(1.0,0.627906976744186)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_E0B_JU1jEfCcZ9y8bwMp1w" type="4001" element="_E0B-TE1jEfCcZ9y8bwMp1w" source="_E0B-uU1jEfCcZ9y8bwMp1w" target="_Gl4gUE1kEfCcZ9y8bwMp1w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_E0B_Jk1jEfCcZ9y8bwMp1w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_E0B_J01jEfCcZ9y8bwMp1w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_E0B_KE1jEfCcZ9y8bwMp1w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_E0B_KU1jEfCcZ9y8bwMp1w" points="[-15, -23, -1197, 567]$[-15, -535, -1197, 55]$[41, -535, -1141, 55]$[41, -542, -1141, 48]$[1011, -542, -171, 48]$[1011, -585, -171, 5]$[1165, -585, -17, 5]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_E0B_Kk1jEfCcZ9y8bwMp1w" id="(1.0,0.6744186046511628)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_E0B_LE1jEfCcZ9y8bwMp1w" type="4001" element="_E0B-T01jEfCcZ9y8bwMp1w" source="_E0B-oE1jEfCcZ9y8bwMp1w" target="_E0B-o01jEfCcZ9y8bwMp1w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_E0B_LU1jEfCcZ9y8bwMp1w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_E0B_Lk1jEfCcZ9y8bwMp1w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_E0B_L01jEfCcZ9y8bwMp1w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_E0B_ME1jEfCcZ9y8bwMp1w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_E0B_MU1jEfCcZ9y8bwMp1w" type="4001" element="_E0B-Uk1jEfCcZ9y8bwMp1w" source="_E0B-wU1jEfCcZ9y8bwMp1w" target="_E0B-o01jEfCcZ9y8bwMp1w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_E0B_Mk1jEfCcZ9y8bwMp1w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_E0B_M01jEfCcZ9y8bwMp1w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_E0B_NE1jEfCcZ9y8bwMp1w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_E0B_NU1jEfCcZ9y8bwMp1w" points="[-5, -20, 50, 220]$[-55, -246, 0, -6]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_E0B_Nk1jEfCcZ9y8bwMp1w" id="(1.0,0.29347826086956524)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_E0B_N01jEfCcZ9y8bwMp1w" id="(0.4883720930232558,0.16279069767441862)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_E0B_P01jEfCcZ9y8bwMp1w" type="4001" element="_E0B-WE1jEfCcZ9y8bwMp1w" source="_E0B-o01jEfCcZ9y8bwMp1w" target="_Gl4gUE1kEfCcZ9y8bwMp1w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_E0B_QE1jEfCcZ9y8bwMp1w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_E0B_QU1jEfCcZ9y8bwMp1w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_E0B_Qk1jEfCcZ9y8bwMp1w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_E0B_Q01jEfCcZ9y8bwMp1w" points="[-22, -25, -644, 237]$[-22, -291, -644, -29]$[622, -291, 0, -29]$[622, -283, 0, -21]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_E0B_RE1jEfCcZ9y8bwMp1w" id="(1.0,0.5813953488372093)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_E0B_Rk1jEfCcZ9y8bwMp1w" type="4001" element="_E0B-W01jEfCcZ9y8bwMp1w" source="_E0B-o01jEfCcZ9y8bwMp1w" target="_UjS2YE1kEfCcZ9y8bwMp1w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_E0B_R01jEfCcZ9y8bwMp1w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_E0B_SE1jEfCcZ9y8bwMp1w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_E0B_SU1jEfCcZ9y8bwMp1w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_E0B_Sk1jEfCcZ9y8bwMp1w" points="[18, 4, -266, -467]$[18, 78, -266, -393]$[94, 78, -190, -393]$[94, 52, -190, -419]$[259, 52, -25, -419]$[259, 484, -25, 13]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_rVQAsE1jEfCcZ9y8bwMp1w" id="(0.5813953488372093,0.18604651162790697)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_E0B_S01jEfCcZ9y8bwMp1w" type="4001" element="_E0B-Xk1jEfCcZ9y8bwMp1w" source="_E0B-o01jEfCcZ9y8bwMp1w" target="_E0B-p01jEfCcZ9y8bwMp1w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_E0B_TE1jEfCcZ9y8bwMp1w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_E0B_TU1jEfCcZ9y8bwMp1w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_E0B_Tk1jEfCcZ9y8bwMp1w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_E0B_T01jEfCcZ9y8bwMp1w" points="[-1, -20, -312, 31]$[-1, -61, -312, -10]$[261, -61, -50, -10]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_E0B_UE1jEfCcZ9y8bwMp1w" type="4001" element="_E0B-YU1jEfCcZ9y8bwMp1w" source="_E0B-qk1jEfCcZ9y8bwMp1w" target="_Gl4gUE1kEfCcZ9y8bwMp1w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_E0B_UU1jEfCcZ9y8bwMp1w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_E0B_Uk1jEfCcZ9y8bwMp1w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_E0B_U01jEfCcZ9y8bwMp1w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_E0B_VE1jEfCcZ9y8bwMp1w" points="[-23, 28, 220, -267]$[-243, 268, 0, -27]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_E0B_VU1jEfCcZ9y8bwMp1w" id="(0.7906976744186046,0.5581395348837209)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_E0B_Vk1jEfCcZ9y8bwMp1w" id="(0.20930232558139536,0.5813953488372093)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_E0B_Yk1jEfCcZ9y8bwMp1w" type="4001" element="_E0B-ak1jEfCcZ9y8bwMp1w" source="_E0B-qk1jEfCcZ9y8bwMp1w" target="_UjS2YE1kEfCcZ9y8bwMp1w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_E0B_Y01jEfCcZ9y8bwMp1w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_E0B_ZE1jEfCcZ9y8bwMp1w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_E0B_ZU1jEfCcZ9y8bwMp1w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_E0B_Zk1jEfCcZ9y8bwMp1w" points="[-8, 14, 249, -536]$[-189, 14, 68, -536]$[-189, 464, 68, -86]$[-184, 464, 73, -86]$[-184, 531, 73, -19]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_E0B_Z01jEfCcZ9y8bwMp1w" id="(0.7906976744186046,0.09302325581395349)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_E0B_aE1jEfCcZ9y8bwMp1w" type="4001" element="_E0B-bU1jEfCcZ9y8bwMp1w" source="_E0B-p01jEfCcZ9y8bwMp1w" target="_E0B-qk1jEfCcZ9y8bwMp1w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_E0B_aU1jEfCcZ9y8bwMp1w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_E0B_ak1jEfCcZ9y8bwMp1w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_E0B_a01jEfCcZ9y8bwMp1w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_E0B_bE1jEfCcZ9y8bwMp1w" points="[-29, 37, 49, -61]$[-77, 119, 1, 21]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_E0B_bU1jEfCcZ9y8bwMp1w" id="(1.0,0.4032258064516129)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_no_KU01jEfCcZ9y8bwMp1w" type="4001" element="_no_KUE1jEfCcZ9y8bwMp1w" source="_jyLQ0E1jEfCcZ9y8bwMp1w" target="_no-jSE1jEfCcZ9y8bwMp1w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_no_xYE1jEfCcZ9y8bwMp1w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_no_xYU1jEfCcZ9y8bwMp1w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_no_KVE1jEfCcZ9y8bwMp1w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_no_KVU1jEfCcZ9y8bwMp1w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_3pmHNE1jEfCcZ9y8bwMp1w" type="4001" element="_3pmHMU1jEfCcZ9y8bwMp1w" source="_no-jSE1jEfCcZ9y8bwMp1w" target="_3plgKU1jEfCcZ9y8bwMp1w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_3pmuQE1jEfCcZ9y8bwMp1w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_3pmuQU1jEfCcZ9y8bwMp1w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_3pmHNU1jEfCcZ9y8bwMp1w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_3pmHNk1jEfCcZ9y8bwMp1w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_XforsE1kEfCcZ9y8bwMp1w" type="4001" element="_XfoEoE1kEfCcZ9y8bwMp1w" source="_UjS2YE1kEfCcZ9y8bwMp1w" target="_jyLQ0E1jEfCcZ9y8bwMp1w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_XfpSwE1kEfCcZ9y8bwMp1w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_XfpSwU1kEfCcZ9y8bwMp1w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_XforsU1kEfCcZ9y8bwMp1w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Xforsk1kEfCcZ9y8bwMp1w" points="[-20, 2, 28, -71]$[-43, 50, 5, -23]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Xfqg4E1kEfCcZ9y8bwMp1w" id="(1.0,0.7906976744186046)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_fY_0oE1kEfCcZ9y8bwMp1w" type="4001" element="_fY_NkE1kEfCcZ9y8bwMp1w" source="_Gl4gUE1kEfCcZ9y8bwMp1w" target="_H0AgUE1kEfCcZ9y8bwMp1w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_fZAbsk1kEfCcZ9y8bwMp1w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_fZAbs01kEfCcZ9y8bwMp1w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_fZAbsE1kEfCcZ9y8bwMp1w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_fZAbsU1kEfCcZ9y8bwMp1w" points="[-4, -2, -123, -28]$[118, 41, -1, 15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_fZBp0E1kEfCcZ9y8bwMp1w" id="(1.0,0.6511627906976745)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_nLECwU1kEfCcZ9y8bwMp1w" type="4001" element="_nLDbsE1kEfCcZ9y8bwMp1w" source="_H0AgUE1kEfCcZ9y8bwMp1w" target="_nLCNkE1kEfCcZ9y8bwMp1w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_nLEp0E1kEfCcZ9y8bwMp1w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_nLEp0U1kEfCcZ9y8bwMp1w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_nLECwk1kEfCcZ9y8bwMp1w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_nLECw01kEfCcZ9y8bwMp1w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_v0n5kk1kEfCcZ9y8bwMp1w" type="4001" element="_v0nSgE1kEfCcZ9y8bwMp1w" source="_3plgKU1jEfCcZ9y8bwMp1w" target="_H0AgUE1kEfCcZ9y8bwMp1w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_v0n5lU1kEfCcZ9y8bwMp1w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_v0n5lk1kEfCcZ9y8bwMp1w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_v0n5k01kEfCcZ9y8bwMp1w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_v0n5lE1kEfCcZ9y8bwMp1w" points="[-1, -32, 17, 794]$[-1, -518, 17, 308]$[-18, -518, 0, 308]$[-18, -796, 0, 30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_v0ogoE1kEfCcZ9y8bwMp1w" id="(1.0,0.4050632911392405)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_v0pHsE1kEfCcZ9y8bwMp1w" id="(0.3488372093023256,0.13953488372093023)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_7NOwk01kEfCcZ9y8bwMp1w" type="4001" element="_7NOwkE1kEfCcZ9y8bwMp1w" source="_H0AgUE1kEfCcZ9y8bwMp1w" target="_7NOJiE1kEfCcZ9y8bwMp1w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_7NPXok1kEfCcZ9y8bwMp1w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_7NPXo01kEfCcZ9y8bwMp1w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_7NPXoE1kEfCcZ9y8bwMp1w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_7NPXoU1kEfCcZ9y8bwMp1w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Cqi2sk1lEfCcZ9y8bwMp1w" type="4001" element="_CqiPok1lEfCcZ9y8bwMp1w" source="_7NOJiE1kEfCcZ9y8bwMp1w" target="_Cqhok01lEfCcZ9y8bwMp1w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Cqi2tU1lEfCcZ9y8bwMp1w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Cqi2tk1lEfCcZ9y8bwMp1w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Cqi2s01lEfCcZ9y8bwMp1w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Cqi2tE1lEfCcZ9y8bwMp1w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_J9EpIE1lEfCcZ9y8bwMp1w" type="4001" element="_J9ECEE1lEfCcZ9y8bwMp1w" source="_Cqhok01lEfCcZ9y8bwMp1w" target="_E0B-2k1jEfCcZ9y8bwMp1w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_J9FQME1lEfCcZ9y8bwMp1w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_J9FQMU1lEfCcZ9y8bwMp1w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_J9EpIU1lEfCcZ9y8bwMp1w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_J9EpIk1lEfCcZ9y8bwMp1w" points="[-18, 7, 39, -522]$[-57, 516, 0, -13]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_J9HFYE1lEfCcZ9y8bwMp1w" id="(1.0,0.7441860465116279)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_J9HFYU1lEfCcZ9y8bwMp1w" id="(0.5875,0.225)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_NDgOkE1lEfCcZ9y8bwMp1w" type="4001" element="_NDfngE1lEfCcZ9y8bwMp1w" source="_7NOJiE1kEfCcZ9y8bwMp1w" target="_nLCNkE1kEfCcZ9y8bwMp1w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_NDgOk01lEfCcZ9y8bwMp1w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_NDgOlE1lEfCcZ9y8bwMp1w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_NDgOkU1lEfCcZ9y8bwMp1w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_NDgOkk1lEfCcZ9y8bwMp1w" points="[-8, -24, 30, 84]$[-34, -119, 4, -11]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_NDiDwE1lEfCcZ9y8bwMp1w" id="(1.0,0.4444444444444444)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_OaRNM01lEfCcZ9y8bwMp1w" type="4001" element="_OaRNME1lEfCcZ9y8bwMp1w" source="_E0B-2k1jEfCcZ9y8bwMp1w" target="_OaQmJE1lEfCcZ9y8bwMp1w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_OaRNNk1lEfCcZ9y8bwMp1w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_OaRNN01lEfCcZ9y8bwMp1w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_OaRNNE1lEfCcZ9y8bwMp1w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_OaRNNU1lEfCcZ9y8bwMp1w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
